spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bazaar
    username: admin
    password: 12419
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
